# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7275b2bc9f9e1928f969ee442c513c05a3439f9f94ebb371e4f711464f4c24bf869b90a51c1fbb823821fa14d35497dff1299b9fb6c15edf9e50401537e9316

test:
  secret_key_base: 6f1e55e0563a42649317f3f335e5b3fe33727f5742098a56043f079c86719fa4404e88798a4bb0fd2cfc90b28fceb6491537f097c29f05558f5d459a268e3bcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
